server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/netbank
    username: netbank
    password: netbank
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
